accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup',views.signup,name='signup'),
    path('profile',views.profile,name='profile'),
    path('profile_edit',views.profile_edit,name='profile_edit'),
    #  path('logout/', views.logout, name='logout'),
]

job/urls.py
from django.urls import path
from . import views

app_name='job'
urlpatterns = [
    path('' , views.job_list , name="job_list"),
    path('add',views.add_job,name="add_job"),
    path('<str:slug>' , views.job_detail , name="job_detail"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jobs/', include('job.urls' , namespace='jobs')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('contact/', include('contact.urls',namespace='contactus')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.
class City(models.Model):
    name= models.CharField(max_length=30)
    
    
    def __str__(self) -> str:
        return self.name
    
    
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    city=models.ForeignKey('City' , related_name='user_city', on_delete= models.CASCADE,blank=True, null=True)
    phone_number = PhoneNumberField(blank=True, null=True)
    image= models.ImageField(upload_to='profile/')
    
    def __str__(self) -> str:
         return self.user.username
    
    
    
@receiver(post_save , sender=User) 
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/views.py
from audioop import reverse
from http.client import HTTPResponse
from django.shortcuts import render, redirect
from .form import SignupForm , UserForm , ProfileForm
from django.contrib.auth import authenticate, login
from .models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from job.views import job_list

app_name="accounts"
def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            phone_number = form.cleaned_data['phone_number']
            image = form.cleaned_data['image']
            city = form.cleaned_data['city']

            Profile.objects.update_or_create(
                user=user,
                defaults={
                    'phone_number': phone_number,
                    'image': image,
                    'city':city
                }
            )
            
            # Authenticate and log in the user
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('profile')
    else:
        form = SignupForm()

    context = {"form": form}
    return render(request, 'registration/signup.html', context)


def profile(request):
    profile=Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{"profile":profile})
@login_required
def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    
    if request.method == "POST":
        userform = UserForm(request.POST, instance=request.user)
        profileform = ProfileForm(request.POST, request.FILES, instance=profile)
        
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile=profileform.save(commit=False)
            myprofile.user=request.user
            myprofile.save()
            return redirect('accounts:profile')  # Redirect to the profile page or wherever appropriate
    else:
        userform = UserForm(instance=request.user)
        profileform = ProfileForm(instance=profile)
    
    context = {
        "userform": userform,
        "profileform": profileform
    }
    return render(request, 'accounts/profile_edit.html', context)


# def logout(request):
#     auth_logout(request)
#     return redirect('accounts:login')  

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{%  load bootstrap4 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{ job.title }}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>UserName: <span>{{ profile }}</span></li>
                                <li>Firs Name: <span>{{profile.user.first_name }}</span></li>
                                <li>Last Name: <span>{{ profile.user.last_name }}</span></li>
                                <li>Email: <span>{{ profile.user.email }}</span></li>
                                <li>Address: <span>{{ profile.city }}</span></li>
                                <li>Phone Number: <span>{{ profile.phone_number }}</span></li>
                            </ul>
                        </div>
                        <div class="p-5">
                            <a href="{% url 'accounts:profile_edit' %}" class ="boxed-btn3 w-100">Edit Profile</a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
        </div>
    </div>
    <!--/ bradcam_area  -->
    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 offset-lg-2"> <!-- Centering the job details area -->
                    <div class="apply_job_form white-bg text-center"> <!-- Centering the form -->
                        <h4>Edit Profile</h4>
                        <form method="POST" enctype='multipart/form-data'>
                            {% csrf_token %}
                            {% bootstrap_form userform %} 
                            {% bootstrap_form profileform %} <!-- Use Bootstrap form rendering -->
                            <button class="boxed-btn3 w-100" type="submit">Save</button>
                        </form>                   
                </div>
            </div>
        </div>
    </div>
{% endblock body %}